'use strict';

const BLUEPRINT=Object.freeze({
  finance:{
    modules:{
      core_accounting:['general_ledger','journal_entries','accounts_payable','accounts_receivable','cash_bank','trial_balance','profit_loss','balance_sheet','cash_flow','fiscal_periods'],
      management_accounting:['cost_centers','profit_centers','budget_control','standard_actual_costing','job_costing','project_costing','variance_analysis','profitability_analysis'],
      assets_treasury:['fixed_assets','depreciation','asset_accounting','treasury','liquidity','forex','multi_currency','bank_reconciliation','payment_factory'],
      enterprise_finance:['multi_company','intercompany','consolidation','transfer_pricing','financial_planning','scenario_modelling','audit_trails','fraud_controls'],
      india_tax:['gst','tds','tcs','e_invoice','e_way_bill','input_tax_credit','tax_reconciliation','statutory_reporting'],
    },
  },
  supply_chain:{
    modules:{
      procurement:['purchase_requisition','rfq','quotation_comparison','purchase_order','blanket_order','rate_contract','three_way_match','invoice_verification'],
      supplier_lifecycle:['vendor_registration','vendor_evaluation','supplier_scorecard','supplier_portal','supplier_risk','esg_supplier_evaluation','contract_lifecycle'],
      inventory:['item_master','stock_ledger','batch','lot','serial','expiry','quality_hold','reorder','safety_stock','abc','xyz','eoq','slow_fast_dead_stock'],
      warehouse:['receiving','grn','putaway','bin_rack','pallet','picking','packing','dispatch','wave_picking','cross_docking','yard','cold_storage','barcode_qr_rfid'],
      planning:['demand_planning','sop','mrp','capacity_planning','inventory_planning','distribution_planning','autonomous_planning'],
      global_trade:['import','export','customs','trade_compliance','container_tracking','port_tracking','export_documentation'],
    },
  },
  sales:{
    modules:{
      commercial:['lead_to_quote','quotation','sales_order','contract','pricing','discount_control','credit_check','order_allocation','invoice','returns'],
      channels:['distributor','dealer','institutional_sales','government_sales','b2b','direct_sales','channel_margin','sales_commission'],
      analytics:['sales_pipeline','order_book','margin_analysis','forecast','customer_profitability','sales_performance'],
    },
  },
  marketing:{
    modules:{
      campaigns:['campaign_management','email_marketing','whatsapp_campaigns','segmentation','attribution','lead_generation','promotion_engine'],
      customer_growth:['loyalty','rewards','coupons','gift_cards','membership','referral','retention','churn'],
      product_market:['market_intelligence','category_management','assortment','seasonality','competitive_pricing','brand_content'],
    },
  },
  logistics:{
    modules:{
      tms:['shipment_planning','load_optimization','route_planning','route_optimization','carrier_management','freight_management','freight_costing','shipment_visibility'],
      fleet:['vehicle_master','gps_tracking','driver_management','fuel','tyre','maintenance','accident','driver_performance','geofencing'],
      delivery:['dispatch','delivery_scheduling','last_mile','proof_of_delivery','failed_delivery','returns_logistics','cold_chain_monitoring'],
      trade_tracking:['consignment_tracking','container_tracking','port_tracking','customs_tracking','yard_management'],
    },
  },
  crm:{
    modules:{
      sales_crm:['leads','opportunities','activities','customer_360','interaction_tracking','journey_tracking'],
      service:['complaints','service_requests','ticketing','sla','escalation','warranty','amc','field_service','knowledge_base'],
      engagement:['communications','customer_feedback','nps','segmentation','case_analytics'],
    },
  },
  erm:{
    modules:{
      master_economic_entities:['person','household','farmer','farm','plot','fpo','cooperative','village','panchayat','rural_enterprise'],
      productive_resources:['crop','animal','poultry','fishery','equipment','warehouse','cold_storage','processing_capacity','community_assets'],
      network:['partner','service_provider','buyer','supplier','laboratory','bank','insurer','government_buyer'],
      capacity:['shared_capacity','booking','utilisation','service_catalogue','rural_infrastructure'],
    },
  },
  workforce:{
    modules:{
      core_hcm:['employee_master','contractor_master','recruitment','onboarding','attendance','leave','shift','biometric','gps_attendance'],
      payroll:['salary','benefits','incentives','statutory_deductions','expense_claims','travel','worker_settlement'],
      talent:['performance','skills','succession','learning_management','training','certification','workforce_planning'],
      field_workforce:['contract_labour','rural_freelancer','work_orders','rate_cards','time_tracking','safety','insurance'],
    },
  },
  insurance:{
    modules:{
      policy:['product_configuration','policy_creation','renewal','endorsement','premium_billing','coverage','beneficiary'],
      underwriting:['risk_assessment','premium_calculation','underwriting_rules','approval','reinsurance'],
      claims:['claim_registration','fnol','investigation','document_collection','reserve','settlement','recovery','subrogation','claim_tracking'],
      distribution:['agent','broker','commission','customer_lifecycle'],
      controls:['fraud_detection','kyc','regulatory_reporting','complaints','audit'],
      rural_risk:['crop_risk','livestock_risk','shipment_risk','asset_risk','weather_parametric'],
    },
  },
  retail:{
    modules:{
      store:['pos','multi_store','franchise','cashier','store_inventory','store_transfer','store_performance'],
      merchandising:['pricing','assortment','shelf_planning','category_management','promotion','markdown','seasonal_planning'],
      customer:['loyalty','rewards','coupons','gift_cards','membership','footfall','customer_analytics'],
      omnichannel:['click_collect','store_pickup','home_delivery','unified_inventory','real_time_stock'],
    },
  },
  ecommerce:{
    modules:{
      pim:['product_catalog','attributes','variants','digital_assets','content','seo'],
      marketplace:['seller_onboarding','amazon','flipkart','meesho','ebay','alibaba','channel_sync'],
      oms:['cart','order_capture','order_tracking','allocation','returns','refunds','cod','cancellation'],
      experience:['reviews','wishlist','recommendation','cart_recovery','personalization','promotion'],
      omnichannel:['click_collect','store_pickup','unified_inventory','real_time_availability'],
    },
  },
  production:{
    modules:{
      engineering:['bom','routing','product_configuration','cad_integration','plm_link','engineering_change'],
      planning:['work_order','production_schedule','capacity','mrp_link','material_issue','batch_plan'],
      shop_floor:['machine_tracking','operator_tracking','wip','tool_tracking','labor_tracking','downtime','oee'],
      process:['recipe','batching','yield','mass_balance','processing','pre_cooling','packaging','labeling'],
      industry40:['iot_sensor','telemetry','predictive_analytics','digital_twin','machine_learning'],
    },
  },
  quality:{
    modules:{
      inspection:['incoming','in_process','final','sampling','quality_hold','release'],
      qms:['ncr','capa','root_cause','audit','complaint_quality','supplier_quality','recall'],
      laboratory:['sample_management','test_method','result','coa','certification','lab_instrument'],
      standards:['iso9001','iso14001','iso45001','gmp','haccp','lean','six_sigma'],
      traceability:['batch_genealogy','lot_trace','certificate_trace','food_safety','biological_quality'],
    },
  },
  asset:{
    modules:{
      lifecycle:['asset_register','acquisition','capitalization','operation','transfer','disposal','depreciation'],
      maintenance:['preventive','predictive','breakdown','work_order','maintenance_plan','equipment_history','rcm'],
      spares:['spare_inventory','reservation','issue','replenishment','critical_spares'],
      reliability:['mtbf','mttr','failure_analysis','condition_monitoring','calibration'],
      tracking:['rfid','gps','ble','mobile_asset','equipment_location','drone_inspection'],
    },
  },
  projects:{
    modules:{
      controls:['project_master','wbs','schedule','resource','budget','cost_tracking','progress','earned_value','risk'],
      epc:['boq','material_tracking','contractor','contractor_billing','site_progress','dpr','rfi','material_reconciliation'],
      engineering:['document_control','drawing_register','bim_integration','change_order','technical_query'],
      grants:['community_project','grant_tracking','funding_milestone','utilisation_certificate'],
    },
  },
  governance:{
    modules:{
      workflow:['approval','multi_level_approval','parallel_approval','escalation','sla','task','digital_signature'],
      grc:['policy','risk_register','control','compliance','internal_audit','external_audit','exception','sod'],
      legal:['contract_repository','legal_case','obligation','notice','litigation_tracking'],
      dms:['document_repository','version_control','lifecycle','ocr','records_retention','engineering_documents','iso_documents'],
      data_governance:['mdm_governance','data_quality','lineage','reference_data','privacy','access_governance'],
      sustainability_governance:['ehs','esg_reporting','carbon_accounting','sustainability_management'],
    },
  },
  data_ai:{
    modules:{
      bi:['dashboard','kpi','mis','executive_report','self_service_analytics','predictive_analytics'],
      ai:['forecasting','recommendation','fraud_analytics','predictive_maintenance','copilot','agentic_ai','autonomous_agents','explainability'],
      knowledge:['knowledge_management','hybrid_retrieval','semantic_search','knowledge_graph','enterprise_memory'],
      digital_twin:['plant_simulation','warehouse_simulation','supply_chain_simulation','scenario_planning'],
      integration:['api_management','event_mesh','workflow_automation','iot_platform','gis','blockchain_traceability'],
      operations:['model_registry','evaluation','guardrails','cost_governance','observability','audit','human_approval'],
    },
  },
});

function listDomains(){return Object.entries(BLUEPRINT).map(([domainId,d])=>({domainId,moduleGroups:Object.keys(d.modules).length,moduleCount:Object.values(d.modules).reduce((n,a)=>n+a.length,0)}));}
function listCapabilities(domainId){
  const domain=BLUEPRINT[domainId];
  if(!domain)return [];
  return Object.entries(domain.modules).flatMap(([moduleGroup,capabilities])=>capabilities.map(capability=>({domainId,moduleGroup,capability})));
}
function allCapabilities(){return Object.keys(BLUEPRINT).flatMap(listCapabilities);}
function summary(){
  const domains=listDomains();
  return {
    domains:domains.length,
    moduleGroups:domains.reduce((n,d)=>n+d.moduleGroups,0),
    capabilityEntries:domains.reduce((n,d)=>n+d.moduleCount,0),
    uniqueCapabilities:new Set(allCapabilities().map(x=>x.capability)).size,
    byDomain:domains,
  };
}
module.exports={BLUEPRINT,listDomains,listCapabilities,allCapabilities,summary};
