const { SignalBus, SIGNAL, SEVERITY } = require('../core/signalBus');
const { EventSchemaRegistry } = require('../core/eventSchemaRegistry');
const { EventNervousSystem } = require('../core/eventNervousSystem');

describe('Event nervous system',()=>{
  it('rejects events that do not satisfy registered schemas',async()=>{const registry=new EventSchemaRegistry();registry.register('quality.test.failed','1.0.0',{required:['lotId']});const n=new EventNervousSystem({bus:new SignalBus(),registry});await expect(n.publish('quality.test.failed',{})).rejects.toMatchObject({code:'EVENT_SCHEMA_INVALID'});});
  it('publishes governed events with strong identifiers and signal compatibility',async()=>{const bus=new SignalBus();const registry=new EventSchemaRegistry();registry.register(SIGNAL.TEMPERATURE_BREACH,'1.0.0',{required:['temp']});const seen=jest.fn();bus.onSignal(SIGNAL.TEMPERATURE_BREACH,seen);const n=new EventNervousSystem({bus,registry});const r=await n.publish(SIGNAL.TEMPERATURE_BREACH,{temp:12},{source:'sensor',entityId:'S1',severity:SEVERITY.CRITICAL});expect(r.event.eventId).toMatch(/^[0-9a-f-]{36}$/);expect(r.event.correlationId).toMatch(/^[0-9a-f-]{36}$/);expect(r.durability).toBe('ephemeral-in-process');expect(seen).toHaveBeenCalledTimes(1);});
  it('runs bounded reflex handlers and reports their result',async()=>{const registry=new EventSchemaRegistry();registry.register('risk.test','1.0.0',{required:['score']});const n=new EventNervousSystem({bus:new SignalBus(),registry});n.registerReflex({id:'r1',type:'risk.test',when:async(e)=>e.payload.score>0.8,act:async()=>({action:'hold'})});const r=await n.publish('risk.test',{score:0.9});expect(r.reflexResults).toEqual([{id:'r1',result:{action:'hold'}}]);});
  it('uses configured durable and queue adapters explicitly',async()=>{const durable={publish:jest.fn()};const queue={enqueue:jest.fn()};const registry=new EventSchemaRegistry();registry.register('ops.test','1.0.0',{});const n=new EventNervousSystem({bus:new SignalBus(),registry,durablePublisher:durable,queuePublisher:queue});const r=await n.publish('ops.test',{x:1},{queue:'critical'});expect(r.durability).toBe('durable-publisher');expect(durable.publish).toHaveBeenCalledTimes(1);expect(queue.enqueue).toHaveBeenCalledWith('critical',expect.objectContaining({type:'ops.test'}));});
  it('reports durability honestly when no durable adapter exists',()=>{const n=new EventNervousSystem({bus:new SignalBus()});expect(n.health().durability).toBe('ephemeral-in-process');});
});
