'use strict';
/** Canonical concept-to-runtime catalog. Nothing removed. Every item classified.
 * Ported from pine-shadow src/lib/os/catalog.ts */

const OS_STAGES = [
  { stage: 0, name: 'Concept reconciliation', target: 'Preserve and classify everything.', exit: 'Every concept has source, meaning, class, kernel vs GitHub.' },
  { stage: 1, name: 'Industry baseline', target: 'Identity, data, APIs, workflows, security, tests, observability.', exit: 'Clerk, remaining grams, journal, CoA, period close, offline queue, traces. GitHub identity stays separate.' },
  { stage: 2, name: 'Sector excellence', target: 'Industry-native journeys.', exit: 'Agriculture living. Claims file without payout. Schemes effective-dated, amount blank. Engineering BOQ stamp lives. Village remaining journey lives. Tourism refused. CFD refused.' },
  { stage: 3, name: 'Intelligent assistance', target: 'Grounded AI on each component.', exit: 'Library, companion, firewall, eval harness, consent receipts. Cell inspect, no login profile. Frontier, agentic, security tissues live. No invented ₹.' },
  { stage: 4, name: 'System intelligence', target: 'Events, agents, knowledge, twins coordinate.', exit: 'Module OS bus. Farm twin on declared loss %. Federated ask is local remaining; national null. One brain. Five tissues. Decision passport.' },
  { stage: 5, name: 'Autonomous ecosystem', target: 'Bounded execution.', exit: 'Low-risk auto-ops run. Climate reflex blocks mill and opens claim. Physical AI is mill/IoT/remaining. Humanoid teleop refused. Clerk still writes remaining.' },
  { stage: 6, name: 'Futuristic platform', target: 'Adaptive economic OS.', exit: 'Village twin from declared remaining/energy/spoilage. Policy lab what-if, amount blank. Infra twin on declared sensors. Artificial scientist hypothesis. Tourism refused.' },
];

function i(id, name, table, stage, level, area, kernel, github, present, missing, next, organs, href, todo) {
  return { id, name, table, stage, level, area, kernel, github, present, missing, next, organs, href, todo };
}

const OS_ITEMS = [
  i('lv-1', 'Transactional platform', 'level', 1, 1, 'platform', 'partial', 'scaffolded', 'Lots, receipts, orders, journal, FPO split.', 'GST, e-invoice, bank rails, 3-way match.', 'Keep kernel. Do not invent a second ledger.', ['erp', 'lot', 'rupee'], '/platform', 'done'),
  i('lv-2', 'Sector digital businesses', 'level', 2, 2, 'sectors', 'partial', 'scaffolded', 'Agriculture walk. Cover, kitchen, next Magh. Engineering BOQ stamp. Village remaining journey.', 'Tourism itinerary, banking, health journeys. Engineering CFD. Agriculture finance/procure.', 'One sector native: spice/horticulture. Others stay named. Tourism refused.', ['crop', 'farmer', 'marketplace'], '/pulse', 'done'),
  i('lv-3', 'Shared ERP / identity / workflow', 'level', 1, 3, 'erp', 'partial', 'duplicated', 'Clerk, remaining grams, Module OS, L1–L12, village CoA, Magh period close with SoD.', 'One GitHub identity. GST, tax, 3-way match.', 'This kernel is the shared bone. GitHub folders stay cadavers until they plug.', ['erp', 'spine', 'module'], '/charter', 'done'),
  i('lv-4', 'India / rural-first access', 'level', 2, 4, 'rural', 'partial', 'documented', 'Vernacular terms, mobile books, assisted companion, offline queue with sync receipt.', 'IVR/SMS, shared-device consent.', 'Assisted operator lives. Offline sync fires. IVR still named.', ['farmer', 'household'], '/companion', 'done'),
  i('lv-5', 'AI nervous system on evidence', 'level', 3, 5, 'ai', 'partial', 'scaffolded', '35 AI analog families classified. Five tissues, decision passport. GitHub cadavers stay cadavers. AI parity false.', 'Model registry, drift, citations, outcome feedback.', 'Library-first. LLM only on miss. Never a rupee write.', ['ai', 'spine', 'module'], '/brain', 'done'),
  i('lv-6', 'Adaptive UX from consented context', 'level', 3, 6, 'ux', 'partial', 'documented', 'Need-based intents. Consent receipts. Non-personalized default.', 'Experimentation and ranking on GitHub.', 'Do not infer caste, religion, health. Voluntary constraints only.', ['farmer', 'household'], '/os', 'done'),
  i('g-sot', 'Single source of truth', 'gap', 0, 3, 'architecture', 'verified', 'disconnected', 'This catalog. 16-link chain. Four-level enhance. Concept → module → feature → user → workflow → rules → database → service → API → authorization → AI → ERP → page → component → test → telemetry.', 'GitHub still has competing registries.', 'Never remove. Classify. Dual-truth.', ['os', 'erp', 'module'], '/os', 'done'),
  i('g-auth', 'Coherent authentication', 'gap', 1, 3, 'security', 'verified', 'disconnected', 'This organism: clerk. No mock JWT, no plaintext users.', 'GitHub authRoutes in-memory + JWT middleware split.', 'Do not mount the mock. Canonicalize on that branch separately.', ['farmer'], '/os', 'done'),
  i('g-journey', 'Industry journeys', 'gap', 2, 2, 'sectors', 'partial', 'scaffolded', 'Agriculture harvest→godown→offtake→settle. Insurance claims file. Logistics PoD. Scheme eligibility. Engineering BOQ stamp. Village remaining journey.', 'Tourism itinerary, banking underwriting, engineering CFD. Agriculture finance/procure stay missing.', 'Finish agriculture. Name the others. Do not clone dashboards.', ['crop', 'orders'], '/pulse', 'done'),
  i('g-adaptive', 'Governed adaptive webpage', 'gap', 3, 6, 'ux', 'partial', 'documented', 'Need-based nav. Consent receipts. No dark patterns.', 'Experimentation on GitHub.', 'Intents only. No inferred sensitive traits.', ['farmer'], '/os', 'done'),
  i('g-ai', 'Governed AI architecture', 'gap', 3, 5, 'ai', 'partial', 'scaffolded', '35 AI families classified. ackAi emits passport or named-missing. Five tissues decide. GitHub living plugs 0.', 'Training, drift, bias, cost, model registry on GitHub.', 'Evidence or hide. Random wrappers are not AI.', ['ai', 'module'], '/brain', 'done'),
  i('g-workflow', 'State-driven workflows', 'gap', 1, 3, 'workflow', 'partial', 'scaffolded', 'harvest-mint, warehouse-intake, offtake-settle, nerve-consult, claim-file, period-close, climate-reflex, remaining-journey, book-muscle. Eleven flow charts.', 'Rental rupees, RFQ, loan, subsidy disbursement, recall. Tourism, CFD stay refused. Finance/procure stay missing.', 'Durable steps persist. Unknown events fail. Charts fire kernel gates.', ['spine', 'lot'], '/flows', 'done'),
  i('g-erp', 'Unified ERP control', 'gap', 1, 3, 'erp', 'partial', 'duplicated', 'Paise journal, remaining, FIFO, WAC, FPO split, trial balance, village CoA, SoD period close. 32 SAP analog families classified. Nested remaining conserves person=home=village.', 'GST, tax, 3-way, bank rec, assets, SAP/Baan/Oracle parity.', 'Journal is the GL of this village. Atlas classifies. Do not invent ₹. Finance/procure stay missing.', ['erp', 'rupee'], '/platform', 'done'),
  i('g-india', 'India-first intelligence', 'gap', 2, 4, 'india', 'partial', 'documented', 'GI mint, Magh kitchen, Langthasa cover, FPO cells, effective-dated PM-KISAN/PMFBY/MIDH/OP-GREEN/NE-LOGISTICS with amount blank.', 'Mandi feed, GST invoice, land registry, gazette twins, disbursement rails.', 'Eligibility may compute. Amount stays undeclared.', ['scheme', 'fpo', 'gcip'], '/trade', 'done'),
  i('g-organism', 'Executable super-organism', 'gap', 0, 1, 'organism', 'partial', 'documented', 'Organs, ligaments, pulse, library, nerve, charter, OS board, human-equivalent body. Immediate reaction reflex names the correct rest.', 'Sensory IoT as full skin, immune fraud, circulatory payments.', 'Map, do not metaphor. Eleven body gates fire. Missing ligaments stay dashed.', ['os', 'spine', 'ai'], '/body', 'done'),
  i('g-data', 'Real analytics lineage', 'gap', 1, 5, 'analytics', 'partial', 'scaffolded', 'Books KPIs from rows. No random dashboards here.', 'GitHub dashboards still simulate.', 'No metric without source.', ['erp', 'rcop'], '/ledger', 'done'),
  i('g-trust', 'Trust and reputation', 'gap', 2, 2, 'trust', 'partial', 'documented', 'GI mint, paymentRef, remaining, evidence passport.', 'Dispute-adjusted scores, appeal, chain of custody network.', 'Passport first. Stars later.', ['trace', 'lot'], '/lots', 'done'),
  i('g-rural', 'Rural-first access complete', 'gap', 2, 4, 'rural', 'partial', 'documented', 'Mobile books, companion assist, vernacular thesis, offline queue with sync receipt.', 'SMS/IVR, shared-device consent, encrypted-at-rest on device.', 'Assisted and offline queue live. IVR still named.', ['farmer', 'household'], '/companion', 'done'),
  i('g-eng', 'Engineering calculation chain', 'gap', 2, 2, 'engineering', 'partial', 'scaffolded', 'BOQ stamp: declared qty+unit+standard+engineer. Amount only if rate declared. CFD refused.', 'BIM, simulation, commissioning on GitHub.', 'Do not fake CFD.', ['shared'], '/os', 'done'),
  i('g-prod', 'Production verification', 'gap', 1, 1, 'ops', 'partial', 'scaffolded', 'Unit tests, typecheck, browser smoke on this kernel.', 'Load, backup restore, pen-test, rollback on GitHub.', 'File existence is not readiness.', ['erp'], '/os', 'done'),
  i('c-organism', 'Digital Super-Organism', 'concept', 0, 1, 'organism', 'partial', 'documented', 'Brain/nerve/memory as library+module OS+charter. Human-equivalent body: skin firewall, mill muscle, remaining vein, pulse heart.', 'Executable immune, payment circulation.', 'OS board maps every metaphor to a service. Body fires eleven gates.', ['os', 'ai', 'spine'], '/body', 'done'),
  i('c-body', 'Human-equivalent body', 'concept', 0, 1, 'organism', 'partial', 'documented', 'Skin firewall, hand clerk, muscle mill, ligament catalog, relax rest, vein remaining, heart pulse, ear mill signals, eye cell inspect, finger grams, feet village ground. Immediate reaction: rest mill is the withdraw reflex. Tourism refused.', 'Full sensory IoT skin, payment circulation as blood, humanoid teleop.', 'Map, do not metaphor. Muscle rests on climate. Remaining moves only on clerk.', ['os', 'farmer', 'lot', 'reflex'], '/body', 'done'),
  i('c-vet', 'Veterinary medical coding', 'concept', 2, 2, 'agriculture', 'partial', 'documented', 'AFRERA-VET living codes on cattle, buffalo, goat, pig, poultry, duck, fish, dog, cat. Headcount conserved. August AI proposes. Clerk/vet confirms. GitHub human ICD refused.', 'SNOMED-VET, WOAH lab confirmation, milk rupees.', 'Map the second genome. Do not dump ICD-10 onto a herd.', ['livestock', 'ai', 'farmer'], '/vet', 'done'),
  i('c-share', 'Shared village muscle', 'concept', 2, 2, 'engineering', 'partial', 'documented', 'Hours conserved on cold bay, mill, mobile/static process and pack, food/soil/animal labs, dryer, polyhouse, equipment pool. FPO owns the muscle. Organic trace lives.', 'Rental rupees, GST invoice, subsidy disbursement, e-way bill.', 'Book hours. Do not invent a rent. GST stays named.', ['shared', 'processing', 'warehouse', 'fpo'], '/share', 'done'),
  i('c-organic', 'Organic tracing', 'concept', 2, 2, 'esg', 'partial', 'documented', 'Lot path mint→intake→process→pack. PGS/NPOP claim is declared. GI lineage conserved. Pack HSN named.', 'Certification network, residue lab confirmation, GST e-invoice.', 'Trace the sack. Do not invent a certificate rupee.', ['trace', 'lot', 'shared'], '/share', 'done'),
  i('c-flows', 'Village flow charts', 'concept', 1, 3, 'workflow', 'partial', 'documented', 'Strategy, work, process, payment, material, vision, decision, command, coordination, algorithms, supply chain. Each node is a kernel gate. Finance/procure/3-way named missing.', 'Bank rails, GST, booking, RFQ, national fan-out.', 'Walk the chart. Do not invent ₹. Missing stay dashed.', ['spine', 'lot', 'rupee'], '/flows', 'done'),
  i('c-modules', 'Modular M001–M150 platform', 'concept', 0, 3, 'modules', 'partial', 'scaffolded', '25 living plugs. Charter 18 criteria.', '~760 GitHub services; WIRED skeletons; duplicates.', 'Registry with runtime status. Do not delete folders.', ['module'], '/modules', 'done'),
  i('c-agri', 'Agriculture operating system', 'concept', 2, 2, 'agriculture', 'partial', 'scaffolded', 'Plot/planting, harvest mint, grade, store, sell, settle. AFRERA-VET codes the second genome.', 'Finance-procure-operate loop, fisheries cashflow, livestock cashflow.', 'Walk is living. Livestock coding lives. Livestock cash stays missing.', ['crop', 'lot', 'farmer', 'livestock'], '/lots', 'done'),
  i('c-erp', 'Enterprise ERP', 'concept', 1, 3, 'erp', 'partial', 'duplicated', 'Village books, platform trial balance, process mass, CoA, Magh period close. Atlas classifies 32 SAP/Baan/Oracle analog families. sapParity false.', 'GST, tax, intercompany, 3-way match, SAP function parity.', 'Connect operational txn to this journal only. Do not claim Oracle.', ['erp', 'rupee'], '/platform', 'done'),
  i('c-erp-atlas', 'Rural ERP atlas', 'concept', 1, 3, 'erp', 'partial', 'documented', '32 analog families classified living/partial/missing/refused. Nested remaining. 18 stakeholders. AI manage emits a passport or named-missing.', 'SAP/Baan/Oracle 100% function, finance rails, procure loop.', 'Classify honestly. Do not paint missing living.', ['erp', 'os', 'ai'], '/platform', 'done'),
  i('c-ai-atlas', 'AI integration atlas', 'concept', 3, 5, 'ai', 'partial', 'documented', '35 AI analog families classified living/partial/missing/refused. ackAi emits a passport or named-missing. Five tissues decide. GitHub living plugs 0. AI parity false.', 'Model registry, OCR, vernacular voice, finance AI, procure AI.', 'Classify honestly. Decision lives. Do not paint cadavers living.', ['ai', 'os', 'spine'], '/brain', 'done'),
  i('c-market', 'Marketplace', 'concept', 2, 2, 'commerce', 'partial', 'scaffolded', 'Offtake, declared price, GI frame, FPO pool.', 'Discovery, returns, trust graph, settlement rails.', 'Listing is born from harvest, not a SKU form.', ['marketplace', 'orders'], '/trade', 'done'),
  i('c-insure', 'Insurance', 'concept', 2, 2, 'insurance', 'partial', 'scaffolded', 'Langthasa godown cover. Claim files without payout. Premium never invented.', 'Need analysis, exclusions, survey, appeal, payout rails.', 'Cover binds. Claim files. Payout stays undeclared.', ['insurance'], '/warehouse', 'done'),
  i('c-bank', 'Banking and rural finance', 'concept', 2, 2, 'finance', 'documented', 'scaffolded', 'Hours-to-pay on the cell. Pledge gate.', 'Underwriting, disbursement, recovery, explainability.', 'No invented credit score.', ['finance', 'farmer'], '/ledger', 'done'),
  i('c-logistics', 'Logistics', 'concept', 2, 2, 'logistics', 'partial', 'scaffolded', 'Declared freight (zero allowed). Spoilage remainder. PoD is a clerk fact. Cold bay hours live. ETA refused.', 'Control tower, load pooling, cold-km energy cost.', 'Freight is a deduction. Do not invent an ETA.', ['logistics'], '/trade', 'done'),
  i('c-eng', 'Engineering platform', 'concept', 2, 2, 'engineering', 'partial', 'scaffolded', 'Professional stamp on declared BOQ. Units and named standard required. CFD refused.', 'BIM, simulation, commissioning on GitHub.', 'CFD stays refused. Stamp is the living joint.', ['shared'], '/os', 'done'),
  i('c-scheme', 'Government schemes', 'concept', 2, 4, 'india', 'partial', 'documented', 'Effective-dated eligibility (PM-KISAN/PMFBY/MIDH/OP-GREEN/NE-LOGISTICS). Amount blank.', 'Gazette twins, disbursement rails.', 'Do not scrape PDFs into a chatbot. Do not invent a rupee.', ['scheme'], '/os', 'done'),
  i('c-auth', 'Authentication', 'concept', 1, 3, 'security', 'verified', 'disconnected', 'Clerk on this kernel. Auth off for visitors.', 'GitHub mock users + JWT split.', 'One identity authority on that branch later.', ['farmer'], '/os', 'done'),
  i('c-personal', 'Personalization', 'concept', 3, 6, 'ux', 'partial', 'documented', 'Need-based intents. Consent receipts. No hidden profile.', 'Ranking engine on GitHub.', 'Voluntary constraints only.', ['farmer', 'household'], '/os', 'done'),
  i('c-ai', 'AI services', 'concept', 3, 5, 'ai', 'partial', 'duplicated', 'One bus, 25 GitHub cadavers, library-first, firewall. One brain, five tissues. Atlas classifies 35 families. AI parity false.', 'GitHub 16 sibling chats. Model registry missing.', 'A wrapper is not production AI. Decision lives on the kernel.', ['ai', 'module'], '/brain', 'done'),
  i('c-access', 'Rural accessibility', 'concept', 2, 4, 'rural', 'partial', 'documented', 'Mobile layout, companion assist, offline queue with sync receipt.', 'IVR, translation review.', 'Assisted operator and offline queue are living.', ['household', 'farmer'], '/companion', 'done'),
  i('c-analytics', 'Analytics', 'concept', 1, 5, 'analytics', 'partial', 'scaffolded', 'KPIs from remaining and journal.', 'Lineage, freshness, experiments on GitHub.', 'Ban simulated business numbers.', ['erp'], '/', 'done'),
  i('c-knowledge', 'Knowledge platform', 'concept', 3, 5, 'knowledge', 'verified', 'scaffolded', 'Library hippocampus, 19+ reflexes, bindings.', 'OCR graph, permissions, cited rules engine.', 'Memory lives without an API key.', ['ai'], '/library', 'done'),
  i('c-esg', 'Sustainability', 'concept', 2, 2, 'esg', 'partial', 'documented', 'Village spoilage grams. Declared kWh. Emissions stay absent.', 'Methodology, factors, audit on GitHub.', 'Do not invent emissions.', ['rcop', 'recie'], '/ledger', 'done'),
];

const OS_ITEM_BY_ID = Object.fromEntries(OS_ITEMS.map((x) => [x.id, x]));

module.exports = { OS_STAGES, OS_ITEMS, OS_ITEM_BY_ID };
