/**
 * Log an analysis/decision result to a user's per-domain history table.
 *
 * Origin: M782 (disease analyzer) -> M052 (crop_diseases) integration,
 * 2026-09-24. That pass found the crop_diseases table is a per-user record
 * log ({id, user_id, data jsonb, status, ...}), not a shared reference
 * catalog, and found the same shape across 12 sibling tables (soil_health,
 * pest_management, irrigation, fertilizer, yield_prediction, crop_insurance,
 * livestock_health, dairy, poultry, fishery, organic_cert, soil_conservation)
 * — all generated by the same scaffold. This helper is the one reusable
 * "record this result to the user's history" call for all of them, instead
 * of copy-pasting the same try/catch per engine.
 *
 * Never throws: a logging failure must not fail the caller's real response.
 */
'use strict';

const { logger } = require('./logger');

/**
 * @param {object} scaffoldService - a module from backend/src/modules/M0xx
 *   (the generic-CRUD scaffold whose .create({user_id, data}) writes to the
 *   matching table — see backend/src/modules/M052/service.js for the shape).
 * @param {string|null|undefined} userId - the authenticated user's id. If
 *   falsy, logging is skipped (the table's user_id column is NOT NULL with
 *   a FK to users — never fabricate one).
 * @param {object} data - the payload to store under the table's `data` jsonb
 *   column. Keep it small and specific to what a history view would show.
 * @returns {Promise<{logged: boolean, id: string|null}>}
 */
async function logToUserHistory(scaffoldService, userId, data) {
  if (!userId) return { logged: false, id: null };
  try {
    const record = await scaffoldService.create({ user_id: userId, data });
    return { logged: true, id: record?.id || null };
  } catch (error) {
    logger.warn('Failed to log result to user history', { error: error.message });
    return { logged: false, id: null };
  }
}

module.exports = { logToUserHistory };
