'use strict';

const { ExternalIntegrationRegistry } = require('./externalIntegrationRegistry');

const DEFINITIONS = Object.freeze({
  razorpay: { provider:'Razorpay', category:'payment', transport:'sdk', authMode:'api-key', capabilities:['create_order','verify_payment_signature','verify_webhook_signature'], requiredEnv:['RAZORPAY_KEY_ID','RAZORPAY_KEY_SECRET'], optionalEnv:['RAZORPAY_WEBHOOK_SECRET'], idempotentOperations:['create_order'], webhookVerification:'hmac-sha256', dataClassifications:['financial','personal'], source:'backend/src/services/razorpayService.js' },
  stripe: { provider:'Stripe', category:'payment', transport:'sdk', authMode:'api-key', capabilities:['payment_intent','confirm_payment','refund','webhook'], requiredEnv:['STRIPE_SECRET_KEY'], optionalEnv:['STRIPE_WEBHOOK_SECRET'], idempotentOperations:['payment_intent','refund'], webhookVerification:'provider-signature', dataClassifications:['financial','personal'], source:'backend/src/integrations/stripeIntegrationComplete.js' },
  twilio: { provider:'Twilio', category:'messaging', transport:'sdk', authMode:'api-key', capabilities:['sms','voice','whatsapp','otp'], requiredEnv:['TWILIO_ACCOUNT_SID','TWILIO_AUTH_TOKEN','TWILIO_PHONE_NUMBER'], optionalEnv:['TWILIO_VOICE_ENABLED','TWILIO_WHATSAPP_FROM','TWILIO_WHATSAPP_NUMBER'], dataClassifications:['personal','sensitive-personal'], source:'backend/src/services/platform/smsAuthService.js' },
  smtp_email: { provider:'SMTP', category:'messaging', transport:'smtp', authMode:'basic', capabilities:['transactional_email'], requiredEnv:['SMTP_HOST','SMTP_USER'], optionalEnv:['SMTP_PASS','SMTP_PASSWORD','SMTP_PORT','SMTP_SECURE','SMTP_FROM','EMAIL_FROM'], dataClassifications:['personal'], source:'backend/src/services/emailService.js' },
  openweather: { provider:'OpenWeather', category:'weather', transport:'https', authMode:'api-key', capabilities:['current_weather','forecast'], requiredEnv:['OPENWEATHER_API_KEY'], dataClassifications:['public','location'], source:'backend/src/services/weatherService.js' },
  imd_mausam: { provider:'IMD Mausam', category:'government', transport:'https', authMode:'none', capabilities:['weather_observation','forecast'], requiredEnv:['IMD_MAUSAM_ENDPOINT'], dataClassifications:['public','location'], source:'backend/src/services/agriculture/weatherService.js' },
  ndma_sachet: { provider:'NDMA SACHET', category:'government', transport:'https', authMode:'none', capabilities:['disaster_alerts'], requiredEnv:['NDMA_SACHET_URL'], dataClassifications:['public','location'], source:'backend/src/services/weather/weatherAlertService.js' },
  gdacs: { provider:'GDACS', category:'government', transport:'https', authMode:'none', capabilities:['global_disaster_alerts'], requiredEnv:['GDACS_URL'], dataClassifications:['public','location'], source:'backend/src/services/weather/weatherAlertService.js' },
  google_oauth: { provider:'Google OAuth', category:'identity', transport:'https', authMode:'oauth2', capabilities:['login','identity_profile'], requiredEnv:['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET','GOOGLE_REDIRECT_URI'], dataClassifications:['personal','identity'], source:'backend/src' },
  facebook_oauth: { provider:'Facebook OAuth', category:'identity', transport:'https', authMode:'oauth2', capabilities:['login','identity_profile'], requiredEnv:['FACEBOOK_CLIENT_ID','FACEBOOK_CLIENT_SECRET','FACEBOOK_REDIRECT_URI'], dataClassifications:['personal','identity'], source:'backend/src' },
  sap_erp: { provider:'SAP', category:'erp', transport:'https', authMode:'custom', capabilities:['party_sync','item_sync','invoice','bill','journal','stock'], requiredEnv:['SAP_HOST','SAP_USER','SAP_PASSWORD'], optionalEnv:['SAP_CLIENT','SAP_PORT','SAP_SYSTEM_ID','SAP_ENABLED'], dataClassifications:['financial','commercial','personal'], source:'backend/src/modules/platform/erp/IntegrationContract.js' },
  oracle_erp: { provider:'Oracle ERP', category:'erp', transport:'https', authMode:'custom', capabilities:['party_sync','item_sync','invoice','bill','journal','stock'], requiredEnv:['ORACLE_HOST','ORACLE_USER','ORACLE_PASSWORD'], optionalEnv:['ORACLE_PORT','ORACLE_SERVICE','ORACLE_ENABLED'], dataClassifications:['financial','commercial','personal'], source:'backend/src/modules/platform/erp/IntegrationContract.js' },
  tally: { provider:'Tally', category:'erp', transport:'https', authMode:'custom', capabilities:['ledger','invoice','voucher'], requiredEnv:['TALLY_URL'], dataClassifications:['financial','commercial'], source:'backend/src/modules/platform/erp/IntegrationContract.js' },
  gsp: { provider:'GST Suvidha Provider', category:'government', transport:'https', authMode:'api-key', capabilities:['e_invoice_irn','cancel_irn','eway_bill'], requiredEnv:['GSP_API_BASE','GSP_API_KEY'], dataClassifications:['financial','regulated'], source:'backend/src/modules/platform/erp/IntegrationContract.js' },
  aws_s3: { provider:'AWS S3', category:'storage', transport:'sdk', authMode:'api-key', capabilities:['object_upload','object_download'], requiredEnv:['AWS_ACCESS_KEY_ID','AWS_SECRET_ACCESS_KEY','AWS_S3_BUCKET','AWS_REGION'], dataClassifications:['internal','personal'], source:'backend/src' },
  elasticsearch: { provider:'Elasticsearch', category:'other', transport:'https', authMode:'custom', capabilities:['search','index'], requiredEnv:['ELASTICSEARCH_URL'], dataClassifications:['internal'], source:'backend/src' },
  sentry: { provider:'Sentry', category:'observability', transport:'https', authMode:'api-key', capabilities:['error_telemetry'], requiredEnv:['SENTRY_DSN'], dataClassifications:['internal'], source:'backend/src' },
  datadog: { provider:'Datadog', category:'observability', transport:'https', authMode:'api-key', capabilities:['metrics','logs','traces'], requiredEnv:['DATADOG_API_KEY'], dataClassifications:['internal'], source:'backend/src' },
  bing_search: { provider:'Bing Search', category:'other', transport:'https', authMode:'api-key', capabilities:['web_search'], requiredEnv:['BING_SEARCH_API_KEY'], dataClassifications:['public'], source:'backend/src' },
  serpapi: { provider:'SerpAPI', category:'other', transport:'https', authMode:'api-key', capabilities:['web_search'], requiredEnv:['SERPAPI_KEY'], dataClassifications:['public'], source:'backend/src' },
  fitbit: { provider:'Fitbit', category:'identity', transport:'https', authMode:'oauth2', capabilities:['wearable_profile','activity','health_metrics'], requiredEnv:['FITBIT_CLIENT_ID','FITBIT_CLIENT_SECRET','FITBIT_REDIRECT_URI'], dataClassifications:['personal','sensitive-personal'], source:'backend/src/services/legacy/wearableIntegrationService.js' },
  zoho_books: { provider:'Zoho Books', category:'erp', transport:'https', authMode:'oauth2', capabilities:['party_sync','invoice','bill','ledger'], requiredEnv:['ZOHO_ACCESS_TOKEN'], dataClassifications:['financial','commercial','personal'], source:'backend/src/modules/platform/erp/ZohoBooksAdapter.js' },
  custom_erp: { provider:'Custom ERP', category:'erp', transport:'https', authMode:'api-key', capabilities:['erp_sync'], requiredEnv:['CUSTOM_ERP_API_URL','CUSTOM_ERP_API_KEY'], dataClassifications:['financial','commercial','personal'], source:'backend/src/services/completeERPIntegrationService.js' },
  data_gov_us: { provider:'Data.gov', category:'government', transport:'https', authMode:'api-key', capabilities:['public_dataset_search','public_dataset_fetch'], requiredEnv:['DATA_GOV_API_KEY'], dataClassifications:['public'], source:'backend/src/services/platform/publicDomainDataExtractionService.js' },
  data_gov_india: { provider:'data.gov.in', category:'government', transport:'https', authMode:'api-key', capabilities:['mandi_prices','public_dataset_fetch'], requiredEnv:['DATA_GOV_IN_KEY'], dataClassifications:['public'], source:'backend/src/jobs/loadMandiPrices.js' },
  dod_public_data: { provider:'US DoD Public Data', category:'government', transport:'https', authMode:'api-key', capabilities:['public_dataset_fetch'], requiredEnv:['DOD_API_KEY'], dataClassifications:['public'], source:'backend/src/services/platform/publicDomainDataExtractionService.js' },
  devin: { provider:'Devin', category:'ai', transport:'https', authMode:'api-key', capabilities:['software_agent_task'], requiredEnv:['DEVIN_API_KEY','DEVIN_API_URL'], dataClassifications:['internal'], source:'backend/src/services/devinService.js' },
  anthropic: { provider:'Anthropic', category:'ai', transport:'https', authMode:'api-key', capabilities:['llm'], requiredEnv:['ANTHROPIC_API_KEY'], optionalEnv:['CLAUDE_API_KEY'], dataClassifications:['internal'], source:'backend/src/services/claude/aiProviderService.js', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  openai: { provider:'OpenAI', category:'ai', transport:'https', authMode:'api-key', capabilities:['llm','vision','image_generation'], requiredEnv:['OPENAI_API_KEY'], optionalEnv:['OPENAI_BASE_URL','OPENAI_MAX_TOKENS','OPENAI_MAX_OUTPUT_TOKENS'], dataClassifications:['internal'], source:'backend/src/services/claude/aiProviderService.js', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  gemini: { provider:'Google Gemini', category:'ai', transport:'https', authMode:'api-key', capabilities:['llm'], requiredEnv:['GEMINI_API_KEY'], optionalEnv:['GEMINI_MAX_TOKENS'], dataClassifications:['internal'], source:'backend/src/services/claude/aiProviderService.js', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  azure_openai: { provider:'Azure OpenAI', category:'ai', transport:'https', authMode:'api-key', capabilities:['llm'], requiredEnv:['AZURE_OPENAI_API_KEY','AZURE_OPENAI_ENDPOINT'], optionalEnv:['AZURE_OPENAI_API_VERSION'], dataClassifications:['internal'], source:'backend/src', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  huggingface: { provider:'Hugging Face Inference', category:'ai', transport:'https', authMode:'api-key', capabilities:['model_inference'], requiredEnv:['HUGGINGFACE_API_KEY'], dataClassifications:['internal'], source:'backend/src/services/claude/aiProviderService.js', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  ollama: { provider:'Ollama', category:'ai', transport:'https', authMode:'none', capabilities:['local_llm'], requiredEnv:['OLLAMA_BASE_URL'], optionalEnv:['OLLAMA_MAX_TOKENS'], dataClassifications:['internal'], source:'backend/src', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  xai: { provider:'xAI/Grok', category:'ai', transport:'https', authMode:'api-key', capabilities:['llm'], requiredEnv:['XAI_API_KEY'], dataClassifications:['internal'], source:'backend/src/lib/organism/fns.js', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  backup_notification_webhook: { provider:'Backup Notification Webhook', category:'observability', transport:'webhook', authMode:'signed-webhook', capabilities:['backup_alert'], requiredEnv:['BACKUP_NOTIFICATION_WEBHOOK'], dataClassifications:['internal'], source:'backend/src/database/backup/backup_manager.js' },
  database_alert_webhook: { provider:'Database Alert Webhook', category:'observability', transport:'webhook', authMode:'signed-webhook', capabilities:['database_alert'], requiredEnv:['DB_ALERT_WEBHOOK'], dataClassifications:['internal'], source:'backend/src/database/monitoring/database_monitor.js' },
  log_aggregation: { provider:'External Log Aggregator', category:'observability', transport:'https', authMode:'api-key', capabilities:['log_export'], requiredEnv:['LOG_AGGREGATION_ENDPOINT'], dataClassifications:['internal'], source:'backend/src' },
});

function buildExternalIntegrationRegistry(options={}) {
  const registry=new ExternalIntegrationRegistry(options);
  for(const [id,definition] of Object.entries(DEFINITIONS)) registry.register(id,definition);
  return registry;
}

module.exports={DEFINITIONS,buildExternalIntegrationRegistry};
