import { useMemo, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { AlertTriangle, CheckCircle2, ClipboardCheck, Factory, Loader2, Scale, ShieldCheck, WalletCards } from 'lucide-react';
import valueChainControlAPI from '../services/valueChainControlAPI';

const initialCase = { title: '', commodity: '', variety: '', state: '', district: '', season: '' };
const number = (value) => Number(value || 0);

function Card({ title, icon: Icon, children }) {
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><span className="rounded-lg bg-emerald-50 p-2 text-emerald-700"><Icon className="h-4 w-4" /></span><h2 className="font-bold text-slate-900">{title}</h2></div>{children}</section>;
}

export default function ValueChainControlCenterPage() {
  const [caseDraft, setCaseDraft] = useState(initialCase);
  const [selectedCaseId, setSelectedCaseId] = useState('');
  const [caseView, setCaseView] = useState(null);
  const [notice, setNotice] = useState('');
  const [price, setPrice] = useState({ deliveredPricePerKg: '', deductions: '' });
  const [mass, setMass] = useState({ harvestQty: '', lossPercent: '' });
  const [assertion, setAssertion] = useState({ fieldKey: '', value: '', evidenceClass: 'USER_DECLARED', sourceSystem: '', sourceRecord: '' });
  const [gateRequirement, setGateRequirement] = useState({ label: '', met: false, blocking: true });
  const casesQuery = useQuery({ queryKey: ['value-chain-control-cases'], queryFn: () => valueChainControlAPI.listCases().then((r) => r.data?.data || []), retry: 1 });
  const capabilitiesQuery = useQuery({ queryKey: ['value-chain-control-capabilities'], queryFn: () => valueChainControlAPI.getCapabilities().then((r) => r.data?.data), retry: 1 });
  const createCase = useMutation({ mutationFn: valueChainControlAPI.createCase, onSuccess: (r) => { setNotice(`Case ${r.data?.data?.case_code || 'created'} is ready for evidence and gate review.`); setCaseDraft(initialCase); setSelectedCaseId(r.data?.data?.id || ''); casesQuery.refetch(); }, onError: () => setNotice('Case creation needs a valid template and authenticated workspace.') });
  const composeCase = useMutation({ mutationFn: ({ id, payload }) => valueChainControlAPI.composeCase(id, payload), onSuccess: (r) => { setCaseView(r.data?.data); setNotice('Control view refreshed from authoritative records.'); }, onError: () => setNotice('Unable to compose this case. Check access and database readiness.') });
  const waterfall = useMutation({ mutationFn: valueChainControlAPI.buildWaterfall, onSuccess: (r) => setNotice(`Farm-gate net: ₹${r.data?.data?.farmGateNetPerKg ?? '—'} / kg`), onError: () => setNotice('Enter a valid delivered price and non-negative deductions.') });
  const massBalance = useMutation({ mutationFn: valueChainControlAPI.projectMassBalance, onSuccess: (r) => setNotice(`Projected saleable output: ${r.data?.data?.saleableQty ?? '—'} kg`), onError: () => setNotice('Enter a positive harvest quantity and a loss under 100%.') });
  const addAssertion = useMutation({ mutationFn: ({ id, payload }) => valueChainControlAPI.assertField(id, payload), onSuccess: () => { setAssertion({ fieldKey: '', value: '', evidenceClass: 'USER_DECLARED', sourceSystem: '', sourceRecord: '' }); setNotice('Evidence assertion stored with its declared provenance class.'); if (selectedCaseId) composeCase.mutate({ id: selectedCaseId }); }, onError: () => setNotice('Assertions require a value, evidence class, and sources for verified records.') });
  const evaluateGate = useMutation({ mutationFn: ({ id, code, requirements }) => valueChainControlAPI.evaluateGate(id, code, requirements), onSuccess: (r) => { setNotice(`Gate ${r.data?.data?.status || 'updated'}; unresolved blockers remain visible.`); if (selectedCaseId) composeCase.mutate({ id: selectedCaseId }); }, onError: () => setNotice('Gate evaluation needs a selected case and valid requirement checklist.') });
  const selected = useMemo(() => (casesQuery.data || []).find((item) => String(item.id) === String(selectedCaseId)), [casesQuery.data, selectedCaseId]);
  const loading = casesQuery.isLoading || capabilitiesQuery.isLoading;

  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6">
    <header className="rounded-3xl bg-slate-950 p-6 text-white shadow-lg"><p className="text-sm font-semibold uppercase tracking-wider text-emerald-300">Authoritative execution workspace</p><h1 className="mt-2 text-3xl font-bold">Value-Chain Control Center</h1><p className="mt-2 max-w-3xl text-sm text-slate-300">Govern product, cold-chain, finance, insurance, subsidy and engineering handoffs with evidence, deterministic calculations and human gates. AI never writes commercial or clinical facts here.</p></header>
    {notice && <div role="status" className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900"><CheckCircle2 className="h-4 w-4" />{notice}</div>}
    {loading ? <div className="flex items-center gap-2 p-8 text-slate-500"><Loader2 className="h-5 w-5 animate-spin" />Loading control-plane contracts…</div> : <>
      <div className="grid gap-4 md:grid-cols-3"><Card title="Controls" icon={ShieldCheck}><p className="text-sm text-slate-600">{capabilitiesQuery.data?.aiBoundary || 'Human approval and authoritative evidence required.'}</p></Card><Card title="Calculations" icon={Scale}><p className="text-2xl font-bold text-slate-900">{capabilitiesQuery.data?.calculations?.length || 0}</p><p className="text-sm text-slate-600">versioned deterministic formulae</p></Card><Card title="Connected domains" icon={Factory}><p className="text-sm text-slate-600">FPO, warehouse receipt, trade escrow and MEP design adapters are visible only when their systems are connected.</p></Card></div>
      <div className="grid gap-6 lg:grid-cols-2"><Card title="Open execution case" icon={ClipboardCheck}><form className="grid gap-3 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); createCase.mutate(caseDraft); }}><input required aria-label="Case title" placeholder="Case title" value={caseDraft.title} onChange={(e) => setCaseDraft({ ...caseDraft, title: e.target.value })} className="rounded-lg border p-2" /><input required aria-label="Commodity" placeholder="Commodity" value={caseDraft.commodity} onChange={(e) => setCaseDraft({ ...caseDraft, commodity: e.target.value })} className="rounded-lg border p-2" />{['variety', 'state', 'district', 'season'].map((key) => <input key={key} aria-label={key} placeholder={key[0].toUpperCase() + key.slice(1)} value={caseDraft[key]} onChange={(e) => setCaseDraft({ ...caseDraft, [key]: e.target.value })} className="rounded-lg border p-2" />)}<button disabled={createCase.isPending} className="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white disabled:opacity-60 sm:col-span-2">{createCase.isPending ? 'Creating…' : 'Create governed case'}</button></form></Card>
      <Card title="Case mission control" icon={Factory}><div className="flex gap-2"><select aria-label="Select case" className="min-w-0 flex-1 rounded-lg border p-2" value={selectedCaseId} onChange={(e) => setSelectedCaseId(e.target.value)}><option value="">Select a case</option>{(casesQuery.data || []).map((item) => <option key={item.id} value={item.id}>{item.case_code} · {item.title}</option>)}</select><button disabled={!selectedCaseId || composeCase.isPending} onClick={() => composeCase.mutate({ id: selectedCaseId })} className="rounded-lg bg-slate-900 px-3 text-sm font-semibold text-white disabled:opacity-50">Refresh</button></div>{selected && <p className="mt-3 text-sm text-slate-600">{selected.commodity} · {selected.state || 'Location pending'} · status: {selected.status}</p>}{caseView && <div className="mt-4 grid grid-cols-2 gap-3 text-sm"><p><b>{caseView.nodes?.length || 0}</b> lifecycle nodes</p><p><b>{caseView.gates?.length || 0}</b> approval gates</p><p><b>{caseView.assertions?.length || 0}</b> evidence assertions</p><p><b>{caseView.links?.length || 0}</b> system links</p></div>}</Card></div>
      <div className="grid gap-6 lg:grid-cols-2"><Card title="Evidence assertion" icon={ClipboardCheck}><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); addAssertion.mutate({ id: selectedCaseId, payload: assertion }); }}><input required disabled={!selectedCaseId} placeholder="Field key (for example lab_moisture_pct)" value={assertion.fieldKey} onChange={(e) => setAssertion({ ...assertion, fieldKey: e.target.value })} className="w-full rounded-lg border p-2 disabled:bg-slate-100" /><input required disabled={!selectedCaseId} placeholder="Value" value={assertion.value} onChange={(e) => setAssertion({ ...assertion, value: e.target.value })} className="w-full rounded-lg border p-2 disabled:bg-slate-100" /><select disabled={!selectedCaseId} value={assertion.evidenceClass} onChange={(e) => setAssertion({ ...assertion, evidenceClass: e.target.value })} className="w-full rounded-lg border p-2"><option>USER_DECLARED</option><option>ESTIMATED</option><option>VERIFIED</option><option>AUTHORITATIVE</option><option>TRANSACTIONAL</option><option>SENSOR_OBSERVED</option></select>{['VERIFIED', 'AUTHORITATIVE', 'TRANSACTIONAL', 'SENSOR_OBSERVED'].includes(assertion.evidenceClass) && <><input required placeholder="Source system" value={assertion.sourceSystem} onChange={(e) => setAssertion({ ...assertion, sourceSystem: e.target.value })} className="w-full rounded-lg border p-2" /><input required placeholder="Source record reference" value={assertion.sourceRecord} onChange={(e) => setAssertion({ ...assertion, sourceRecord: e.target.value })} className="w-full rounded-lg border p-2" /></>}<button disabled={!selectedCaseId || addAssertion.isPending} className="rounded-lg border border-emerald-700 px-4 py-2 font-semibold text-emerald-800 disabled:opacity-50">Record evidence</button></form></Card>
      <Card title="Approval gates" icon={ShieldCheck}>{caseView?.gates?.length ? <div className="space-y-3">{caseView.gates.map((gate) => <form key={gate.id || gate.gate_code} className="rounded-xl border border-slate-200 p-3" onSubmit={(e) => { e.preventDefault(); const existing = Array.isArray(gate.requirements) ? gate.requirements : []; evaluateGate.mutate({ id: selectedCaseId, code: gate.gate_code, requirements: [...existing, { id: `${gate.gate_code}-${Date.now()}`, ...gateRequirement }] }); }}><div className="flex items-center justify-between gap-2"><b className="text-sm">{gate.label}</b><span className={`rounded-full px-2 py-1 text-xs font-semibold ${gate.status === 'passed' ? 'bg-emerald-100 text-emerald-800' : gate.status === 'blocked' ? 'bg-red-100 text-red-800' : 'bg-slate-100 text-slate-700'}`}>{gate.status}</span></div><div className="mt-2 flex flex-wrap gap-2"><input required aria-label={`Requirement for ${gate.label}`} placeholder="Requirement" value={gateRequirement.label} onChange={(e) => setGateRequirement({ ...gateRequirement, label: e.target.value })} className="min-w-40 flex-1 rounded border p-2 text-sm" /><label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={gateRequirement.met} onChange={(e) => setGateRequirement({ ...gateRequirement, met: e.target.checked })} />met</label><button disabled={evaluateGate.isPending} className="rounded border px-2 text-xs font-semibold">Update</button></div></form>)}</div> : <p className="text-sm text-slate-500">Select and refresh a case to review its required approvals.</p>}</Card></div>
      <div className="grid gap-6 lg:grid-cols-2"><Card title="Price waterfall" icon={WalletCards}><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); const deductions = price.deductions.split(',').filter(Boolean).map((amount, i) => ({ label: `Deduction ${i + 1}`, amount: number(amount) })); waterfall.mutate({ deliveredPricePerKg: number(price.deliveredPricePerKg), deductions }); }}><input required inputMode="decimal" placeholder="Delivered price per kg (₹)" value={price.deliveredPricePerKg} onChange={(e) => setPrice({ ...price, deliveredPricePerKg: e.target.value })} className="w-full rounded-lg border p-2" /><input inputMode="decimal" placeholder="Deductions per kg, comma separated" value={price.deductions} onChange={(e) => setPrice({ ...price, deductions: e.target.value })} className="w-full rounded-lg border p-2" /><button className="rounded-lg border border-emerald-700 px-4 py-2 font-semibold text-emerald-800">Calculate net</button></form></Card>
      <Card title="Mass-balance projection" icon={Scale}><form className="space-y-3" onSubmit={(e) => { e.preventDefault(); massBalance.mutate({ harvestQty: number(mass.harvestQty), stages: [{ name: 'planned handling loss', lossFraction: number(mass.lossPercent) / 100 }] }); }}><input required inputMode="decimal" placeholder="Harvest quantity (kg)" value={mass.harvestQty} onChange={(e) => setMass({ ...mass, harvestQty: e.target.value })} className="w-full rounded-lg border p-2" /><input required inputMode="decimal" placeholder="Expected handling loss (%)" value={mass.lossPercent} onChange={(e) => setMass({ ...mass, lossPercent: e.target.value })} className="w-full rounded-lg border p-2" /><button className="rounded-lg border border-emerald-700 px-4 py-2 font-semibold text-emerald-800">Project output</button></form></Card></div>
      <div className="flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><AlertTriangle className="h-5 w-5 shrink-0" />Financial, insurance, subsidy, compliance and medical decisions require verified evidence and authorized human review. This workspace will not fabricate those records.</div>
    </>}</main>;
}
