from pathlib import Path
p=Path(r"C:\Users\DIYA GOEL\Downloads\EBDESIGN\tools\build-ui-experience-catalog.js")
t=p.read_text(encoding="utf-8")
t=t.replace(
" pages.push({file:rel,explicitRoutes,autoRoute:fileToAutoPath(file),apiRefs,fetchRefs,serviceImports,responsive,accessibility,loadingState:loading,errorState:error,emptyState:empty,bytes:Buffer.byteLength(text)});",
" const enterpriseDynamic=rel.startsWith('frontend/src/pages/enterprise-generated/') && /\\/P\\d{3}Page\\.jsx$/.test(rel);\\n pages.push({file:rel,explicitRoutes,autoRoute:fileToAutoPath(file),enterpriseDynamic,dynamicRoute:enterpriseDynamic?'/enterprise/page/:pageId':null,apiRefs,fetchRefs,serviceImports,responsive,accessibility,loadingState:loading,errorState:error,emptyState:empty,bytes:Buffer.byteLength(text)});"
)
t=t.replace(
"const autoRoutes=pages.filter(p=>!explicitPaths.has(p.autoRoute)).map(p=>({path:p.autoRoute,file:p.file,role:p.autoRoute.startsWith('/admin')?'admin':null}));",
"const potentialAutoRoutes=pages.filter(p=>!explicitPaths.has(p.autoRoute)).map(p=>({path:p.autoRoute,file:p.file,role:p.autoRoute.startsWith('/admin')?'admin':null,active:false}));"
)
t=t.replace(
"const orphanPages=pages.filter(p=>p.explicitRoutes.length===0 && !autoRoutes.some(a=>a.file===p.file));",
"const orphanPages=pages.filter(p=>p.explicitRoutes.length===0 && !p.enterpriseDynamic);"
)
old="const summary={schemaVersion:1,generatedAt:new Date().toISOString(),explicitRouteCount:explicit.length,routeGroups:Object.fromEntries(Object.entries(routeGroups).map(([k,v])=>[k,v.length])),pageFileCount:pages.length,autoDiscoveredRouteCount:autoRoutes.length,duplicateExplicitPathCount:duplicatePaths.length,orphanPageCount:orphanPages.length,pagesWithApiEvidence:pages.filter(p=>p.apiRefs.length||p.fetchRefs.length||p.serviceImports.length).length,pagesWithResponsiveEvidence:pages.filter(p=>p.responsive).length,pagesWithAccessibilityEvidence:pages.filter(p=>p.accessibility).length,pagesWithLoadingState:pages.filter(p=>p.loadingState).length,pagesWithErrorState:pages.filter(p=>p.errorState).length,pagesWithEmptyState:pages.filter(p=>p.emptyState).length,activeRouter:'frontend/src/App.jsx + frontend/src/config/routes.js',legacyRouter:{file:'frontend/src/router/routes.jsx',importedByApp:legacyImported},guardImplementations:['frontend/src/components/RouteGuard.jsx','frontend/src/components/ProtectedRoute.jsx'],rules:['Auto-discovered page exposure is catalogued separately from explicit route governance.','Page existence does not prove API/workflow integration.','Legacy router and duplicate guard implementations are reconciliation candidates; no deletion in this phase.','Responsive/accessibility/state flags are source evidence only, not certification.']};"
new="const summary={schemaVersion:2,generatedAt:new Date().toISOString(),explicitRouteCount:explicit.length,routeGroups:Object.fromEntries(Object.entries(routeGroups).map(([k,v])=>[k,v.length])),pageFileCount:pages.length,potentialAutoRouteCount:potentialAutoRoutes.length,activeAutoRouteCount:0,enterpriseDynamicPageCount:pages.filter(p=>p.enterpriseDynamic).length,duplicateExplicitPathCount:duplicatePaths.length,unroutedPageCount:orphanPages.length,pagesWithApiEvidence:pages.filter(p=>p.apiRefs.length||p.fetchRefs.length||p.serviceImports.length).length,pagesWithResponsiveEvidence:pages.filter(p=>p.responsive).length,pagesWithAccessibilityEvidence:pages.filter(p=>p.accessibility).length,pagesWithLoadingState:pages.filter(p=>p.loadingState).length,pagesWithErrorState:pages.filter(p=>p.errorState).length,pagesWithEmptyState:pages.filter(p=>p.emptyState).length,activeRouter:'frontend/src/App.jsx + frontend/src/config/routes.js',enterpriseDynamicRoute:'/enterprise/page/:pageId (ProtectedRoute)',legacyRouter:{file:'frontend/src/router/routes.jsx',importedByApp:legacyImported},canonicalGuard:'frontend/src/components/RouteGuard.jsx',compatibilityGuard:'frontend/src/components/ProtectedRoute.jsx',rules:['autoPageRoutes.js is currently unreferenced; generated paths are potential only and are not counted as live routes.','Enterprise-generated P001-P790 pages are live only through the authenticated dynamic resolver.','Unknown-role pages are not auto-exposed merely to eliminate routing gaps.','Page existence does not prove API/workflow integration.','Responsive/accessibility/state flags are source evidence only, not certification.']};"
if old not in t: raise RuntimeError("summary block not found")
t=t.replace(old,new)
t=t.replace("fs.writeFileSync(path.join(outDir,'auto-routes.json'),JSON.stringify(autoRoutes,null,2)+'\\n');","fs.writeFileSync(path.join(outDir,'potential-auto-routes.json'),JSON.stringify(potentialAutoRoutes,null,2)+'\\n');")
p.write_text(t,encoding="utf-8")
print("ui catalog semantics upgraded")
