from pathlib import Path
p=Path(r"C:\Users\DIYA GOEL\Downloads\EBDESIGN\backend\src\core\integration\externalIntegrationCatalog.js")
t=p.read_text(encoding="utf-8")
anchor="  serpapi: { provider:'SerpAPI', category:'other', transport:'https', authMode:'api-key', capabilities:['web_search'], requiredEnv:['SERPAPI_KEY'], dataClassifications:['public'], source:'backend/src' },\n"
if anchor not in t:
    raise RuntimeError("serpapi anchor missing")
extra=anchor+"""  fitbit: { provider:'Fitbit', category:'identity', transport:'https', authMode:'oauth2', capabilities:['wearable_profile','activity','health_metrics'], requiredEnv:['FITBIT_CLIENT_ID','FITBIT_CLIENT_SECRET','FITBIT_REDIRECT_URI'], dataClassifications:['personal','sensitive-personal'], source:'backend/src/services/legacy/wearableIntegrationService.js' },
  zoho_books: { provider:'Zoho Books', category:'erp', transport:'https', authMode:'oauth2', capabilities:['party_sync','invoice','bill','ledger'], requiredEnv:['ZOHO_ACCESS_TOKEN'], dataClassifications:['financial','commercial','personal'], source:'backend/src/modules/platform/erp/ZohoBooksAdapter.js' },
  custom_erp: { provider:'Custom ERP', category:'erp', transport:'https', authMode:'api-key', capabilities:['erp_sync'], requiredEnv:['CUSTOM_ERP_API_URL','CUSTOM_ERP_API_KEY'], dataClassifications:['financial','commercial','personal'], source:'backend/src/services/completeERPIntegrationService.js' },
  data_gov_us: { provider:'Data.gov', category:'government', transport:'https', authMode:'api-key', capabilities:['public_dataset_search','public_dataset_fetch'], requiredEnv:['DATA_GOV_API_KEY'], dataClassifications:['public'], source:'backend/src/services/platform/publicDomainDataExtractionService.js' },
  data_gov_india: { provider:'data.gov.in', category:'government', transport:'https', authMode:'api-key', capabilities:['mandi_prices','public_dataset_fetch'], requiredEnv:['DATA_GOV_IN_KEY'], dataClassifications:['public'], source:'backend/src/jobs/loadMandiPrices.js' },
  dod_public_data: { provider:'US DoD Public Data', category:'government', transport:'https', authMode:'api-key', capabilities:['public_dataset_fetch'], requiredEnv:['DOD_API_KEY'], dataClassifications:['public'], source:'backend/src/services/platform/publicDomainDataExtractionService.js' },
  devin: { provider:'Devin', category:'ai', transport:'https', authMode:'api-key', capabilities:['software_agent_task'], requiredEnv:['DEVIN_API_KEY','DEVIN_API_URL'], dataClassifications:['internal'], source:'backend/src/services/devinService.js' },
  anthropic: { provider:'Anthropic', category:'ai', transport:'https', authMode:'api-key', capabilities:['llm'], requiredEnv:['ANTHROPIC_API_KEY'], optionalEnv:['CLAUDE_API_KEY'], dataClassifications:['internal'], source:'backend/src/services/claude/aiProviderService.js', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  openai: { provider:'OpenAI', category:'ai', transport:'https', authMode:'api-key', capabilities:['llm','vision','image_generation'], requiredEnv:['OPENAI_API_KEY'], optionalEnv:['OPENAI_BASE_URL','OPENAI_MAX_TOKENS','OPENAI_MAX_OUTPUT_TOKENS'], dataClassifications:['internal'], source:'backend/src/services/claude/aiProviderService.js', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  gemini: { provider:'Google Gemini', category:'ai', transport:'https', authMode:'api-key', capabilities:['llm'], requiredEnv:['GEMINI_API_KEY'], optionalEnv:['GEMINI_MAX_TOKENS'], dataClassifications:['internal'], source:'backend/src/services/claude/aiProviderService.js', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  azure_openai: { provider:'Azure OpenAI', category:'ai', transport:'https', authMode:'api-key', capabilities:['llm'], requiredEnv:['AZURE_OPENAI_API_KEY','AZURE_OPENAI_ENDPOINT'], optionalEnv:['AZURE_OPENAI_API_VERSION'], dataClassifications:['internal'], source:'backend/src', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  huggingface: { provider:'Hugging Face Inference', category:'ai', transport:'https', authMode:'api-key', capabilities:['model_inference'], requiredEnv:['HUGGINGFACE_API_KEY'], dataClassifications:['internal'], source:'backend/src/services/claude/aiProviderService.js', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  ollama: { provider:'Ollama', category:'ai', transport:'https', authMode:'none', capabilities:['local_llm'], requiredEnv:['OLLAMA_BASE_URL'], optionalEnv:['OLLAMA_MAX_TOKENS'], dataClassifications:['internal'], source:'backend/src', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  xai: { provider:'xAI/Grok', category:'ai', transport:'https', authMode:'api-key', capabilities:['llm'], requiredEnv:['XAI_API_KEY'], dataClassifications:['internal'], source:'backend/src/lib/organism/fns.js', notes:'Runtime readiness is governed by Phase 42 AI capability catalog.' },
  backup_notification_webhook: { provider:'Backup Notification Webhook', category:'observability', transport:'webhook', authMode:'signed-webhook', capabilities:['backup_alert'], requiredEnv:['BACKUP_NOTIFICATION_WEBHOOK'], dataClassifications:['internal'], source:'backend/src/database/backup/backup_manager.js' },
  database_alert_webhook: { provider:'Database Alert Webhook', category:'observability', transport:'webhook', authMode:'signed-webhook', capabilities:['database_alert'], requiredEnv:['DB_ALERT_WEBHOOK'], dataClassifications:['internal'], source:'backend/src/database/monitoring/database_monitor.js' },
  log_aggregation: { provider:'External Log Aggregator', category:'observability', transport:'https', authMode:'api-key', capabilities:['log_export'], requiredEnv:['LOG_AGGREGATION_ENDPOINT'], dataClassifications:['internal'], source:'backend/src' },
"""
t=t.replace(anchor,extra,1)
p.write_text(t,encoding="utf-8")
print("external provider catalog expanded")
